name: Build and Run Docker Backup Test

on:
  push:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar repositorio
        uses: actions/checkout@v3

      - name: 🐳 Instalar Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: 🛠️ Construir imagen de prueba
        run: |
          cd docker-backup
          sudo docker build -f Dockerfile.test -t backup-test .

      - name: ▶️ Ejecutar backup de prueba
        run: |
          sudo docker run --rm backup-test
