name: Build and Run Docker Backup

on:
  push:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar repositorio
        uses: actions/checkout@v3

      - name: 🐳 Instalar Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: 🛠️ Construir imagen Docker
        run: |
          cd docker-backup
          sudo docker build -t backup-script .

      - name: ▶️ Ejecutar contenedor de prueba
        run: |
          sudo docker run --rm backup-script
